config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'answers#new'

  resources :questions do
    resources :answers, only: [:show, :index, :new, :create]
  end

  resources :users do
    resources :answers, only: [:show, :index, :new, :create]
  end

  get 'tags/:tag', to: 'answers#index', as: :tag

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
  acts_as_taggable

  validates :answer, presence: true

end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers
  has_many :users, through: :answers
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :answers
  has_many :questions, through: :answers

  validates :user_name, presence: true, uniqueness: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable, :recoverable,
  devise :database_authenticatable, :registerable,
          :rememberable, :trackable, :validatable

  
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  
before_action :authenticate_user!, except: [:index, :show, :new]

  def index
    if params[:tag]
      @answers = Answer.tagged_with(params[:tag])
    else
      @answers = Answer.all
    end
  end

  def show  
    @answer = Answer.find(params[:id]).order(created_at: :asc)
  end

  def new
    @daily = Question.find_by(show_month: Time.now.month, show_day: Time.now.day)
    @answer = Answer.new
  end
 
  def create
    @question = Question.find(params[:question_id])
    @answer = Answer.new( answer_params )
    @answer.user_id = current_user.id
    @answer.question_id = @question.id
    if @answer.save
      redirect_to @question
    else
      flash[:error] = "You must submit an answer"
      redirect_to root_path
    end
  end

  def tagged
    if params[:tag].present? 
      @answers = Answer.tagged_with(params[:tag])
    else 
      @answers = Answer.postall
    end  
  end

  private

  def answer_params
      params.require(:answer).permit(:answer, :user_id, :question_id, :tag_list, :latitude, :longitude)
  end

end




  
 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :user_name
    devise_parameter_sanitizer.for(:sign_up) << :home_city
    devise_parameter_sanitizer.for(:sign_up) << :home_state
    devise_parameter_sanitizer.for(:sign_up) << :home_country
    devise_parameter_sanitizer.for(:sign_up) << :gender
  end



end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.all
  end

  def show
    @question = Question.find( params[:id] )
    @answer = Answer.new
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.all.order(:user_name)
  end

  def show
    @user = User.find( params[:id] )
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
    include ActsAsTaggableOn::TagsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

 
end

app/views/answers/_form.html.erb
<%= form_for [@daily, @answer] do |answer| %>

  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h3><%= answer.label :answer, "Submit Your Answer", :class => "answer-txt" %></h3><br>
  <%= answer.text_area :answer, :class => "answer" %>

  <h3><%= answer.label :tags, "Tags (separate by commas, use '-' with multi-word tags)"%></h3><br>
  <%= answer.text_field :tag_list, :class => "tags" %><br><br>

  <%= answer.submit 'Add Your Answer', :class => 'answer-sub'%>
<% end %>

app/views/answers/edit.html.erb
<%= render 'form' %>

app/views/answers/index.html.erb
<div id="tag_cloud">
  <% tag_cloud Answer.tag_counts, %w[s m l] do |tag, css_class| %>
    <%= link_to tag.name, tag_path(tag.name), class: css_class %>
  <% end %>
</div>

<% @user.questions.uniq.each do |question| %>
  <h3><div class="answer"><%= question.question %> </div></h3>
    <% question.answers.each do |answer| %>
    <% if answer.user == @user %>
      <div class="answer"><%= answer.answer %> <%= answer.created_at.strftime("(%Y)") %></div>
      Tags: <%= raw answer.tags.map { |t| link_to t.name, tag_path(t.name) }.join(', ') %>
    <% end %>
  <% end %>
<% end %>

app/views/answers/new.html.erb
<header class="dailyq">  
  <h1><%= @daily.question %></h1>
  <% if user_signed_in? %>
      <%= render 'form' %>
      <% else %>
      <h2>Please <%= link_to 'Sign In', new_user_session_path %> to submit an answer.</h2>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Annual.li</title>
  <link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" src="//normalize-css.googlecode.com/svn/trunk/normalize.css" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src=uilang.js></script>
</head>
<body>

<nav>
  <ul>
    <li>
      <% if user_signed_in? %> 
        <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to 'Sign In', new_user_session_path %>
      <% end %>
    </li> 
    <li><%= link_to 'See Today\'s Question', root_path %>|</li>
    <li><%= link_to 'See All Questions', questions_path %>|</li>
    <li><%= link_to 'See All Users', users_path %>|</li>
    <li>
      <% if current_user %>
        <%= link_to 'See Your Answers', user_path(current_user) %></li>
      <% end %>
  </ul>
</nav>

<div>
  <%= flash[:error] %>
</div>
 

<%= yield %>



</body>
</html>

app/views/questions/index.html.erb
<header>
  <h2>The Daily Questions</h2>
</header>

<div class="question-list">
  <ul>
    <% @questions.each do |question| %>
      <li><%= question.show_month %>/<%= question.show_day %> - <%= link_to question.question, question %> </li>
    <% end %>
  </ul>
</div>

app/views/questions/show.html.erb
<header>
  <h2>Question for <%= @question.show_month %>/<%= @question.show_day %>:</h2>
  <h2><%= @question.question %></h2>
</header>

<div class="form-ind">
<%= form_for [@question, @answer] do |answer| %>

  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <%= answer.text_area :answer, :class => "answer-ind", :placeholder => "Submit Your Answer" %><br><br>

  
  <%= answer.text_field :tag_list, :class => "tags-ind", :placeholder => "Tags (separate by commas)"%><br><br>

  <%= answer.submit 'Add Your Answer', :class => 'answer-sub-ind'%>
<% end %>
</div>

<div class="question-list">

  <h3>Answers</h3>

  <% @question.answers.each do |answer| %>
    <%= answer.answer %> <%= answer.created_at.strftime("(%Y)") %><br>
  <% end %>

</div>

app/views/tags/show.html.erb
<h2>Answers tagged with: <%= @tag.name %></h2>

<% @tag.answers.each do |tags| %>
  <h3><%= question.question %> </h3>
    <% question.answers.each do |answer| %>
      <%= answer.answer %> <%= answer.created_at.strftime("(%Y)") %>
      Tags: <%= raw answer.tags.map { |t| link_to t.name, tag_path(t.name) }.join(', ') %>
  <% end %>
<% end %>

app/views/users/index.html.erb
<header>
  <h2>All of our members</h2>
</header>

<div class="question-list">
  <ul>
    <% @users.each do |user| %>
      <li><%= link_to user.user_name, user %> </li>
    <% end %>
  </ul>
</div>

app/views/users/show.html.erb
<header>
  <h2>Welcome <%= @user.user_name %></h2>
</header>

<div class="question-list">
  <h3>Your Questions and Answers</h3>
    <% @user.questions.order("id ASC").uniq.each do |question| %>
      <h3><%= question.show_month %>/<%= question.show_day %> - <%= question.question %></h3>
        <% question.answers.each do |answer| %>
        <% if answer.user == @user %>
          <p><%= answer.created_at.strftime("%Y:") %> <%= answer.answer %> - 
          <%= answer.tag_list %></p>
          <!-- Tags: <%= raw answer.tags.map { |t| link_to t.name, tag_path(t.name) }.join(', ') %> --> 
        <% end %>
      <% end %><hr>
    <% end %>
  </div>